package com.doximity.realtimewatchlist_krishna_doximity.ui.theme

import androidx.compose.ui.graphics.Color

val Surface = Color(0xFFFAF8FF)
val SurfaceDim = Color(0xFFD2D9F4)
val SurfaceBright = Color(0xFFFAF8FF)
val SurfaceContainerLowest = Color(0xFFFFFFFF)
val SurfaceContainerLow = Color(0xFFF2F3FF)
val SurfaceContainer = Color(0xFFEAEDFF)
val SurfaceContainerHigh = Color(0xFFE2E7FF)
val SurfaceContainerHighest = Color(0xFFDAE2FD)
val OnSurface = Color(0xFF131B2E)
val OnSurfaceVariant = Color(0xFF434655)
val InverseSurface = Color(0xFF283044)
val InverseOnSurface = Color(0xFFEEF0FF)
val Outline = Color(0xFF737686)
val OutlineVariant = Color(0xFFC3C6D7)
val SurfaceTint = Color(0xFF0053DB)
val Primary = Color(0xFF004AC6)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF2563EB)
val OnPrimaryContainer = Color(0xFFEEEFFF)
val InversePrimary = Color(0xFFB4C5FF)
val Secondary = Color(0xFF505F76)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFD0E1FB)
val OnSecondaryContainer = Color(0xFF54647A)
val Tertiary = Color(0xFF006242)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF007D55)
val OnTertiaryContainer = Color(0xFFBDFFDB)
val Error = Color(0xFFBA1A1A)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFFFDAD6)
val OnErrorContainer = Color(0xFF93000A)
val Background = Color(0xFFFAF8FF)
val OnBackground = Color(0xFF131B2E)
val SurfaceVariant = Color(0xFFDAE2FD)
